# Generated by Django 4.2.2 on 2023-06-14 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('catering', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descuento', models.IntegerField(default=0)),
                ('lugar', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.evento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('cantidadPersonal', models.IntegerField(default=0)),
                ('cantidadInvitados', models.IntegerField(default=0)),
                ('cantidadMesas', models.IntegerField(default=0)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='logic.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(max_length=50)),
                ('fechaInicial', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.reserva')),
            ],
        ),
    ]
