# Generated by Django 4.2.2 on 2023-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='userId',
            field=models.CharField(default='ad72daa11404403', editable=False, max_length=16, primary_key=True, serialize=False),
        ),
    ]
